apiVersion: apps/v1
kind: Deployment
metadata:
  name: rajds-control-plane-fe
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: rajds-control-plane-fe
  template:
    metadata:
      labels:
        app: rajds-control-plane-fe
    spec:
      containers:
      - name: rajds-control-plane-fe
        image: {{ .Values.controlPlanFrontendImage }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rajds-control-plane-fe
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: rajds-control-plane-fe
  ports:
  - name: http
    port: 80
    targetPort: 80
