apiVersion: v1
kind: Service
metadata:
  name: cp
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: rajds-control-plane
  ports:
  - name: grpc
    port: 31234
    targetPort: 31234
  - name: http
    port: 31313
    targetPort: 31313
